// Flutter IDE Mobile - Virtual File System Entity

import 'package:flutter/foundation.dart';

/// Represents a file or directory in the virtual file system
@immutable
class FileEntity {
  final String id;
  final String name;
  final String path;
  final FileEntityType type;
  final String content;
  final DateTime createdAt;
  final DateTime modifiedAt;
  final bool isDirty;
  final List<FileEntity> children;
  final String? extension;

  const FileEntity({
    required this.id,
    required this.name,
    required this.path,
    required this.type,
    this.content = '',
    required this.createdAt,
    required this.modifiedAt,
    this.isDirty = false,
    this.children = const [],
    this.extension,
  });

  /// Create a new file
  factory FileEntity.file({
    required String id,
    required String name,
    required String path,
    String content = '',
  }) {
    return FileEntity(
      id: id,
      name: name,
      path: path,
      type: FileEntityType.file,
      content: content,
      createdAt: DateTime.now(),
      modifiedAt: DateTime.now(),
      extension: _getExtension(name),
    );
  }

  /// Create a new directory
  factory FileEntity.directory({
    required String id,
    required String name,
    required String path,
    List<FileEntity> children = const [],
  }) {
    return FileEntity(
      id: id,
      name: name,
      path: path,
      type: FileEntityType.directory,
      content: '',
      createdAt: DateTime.now(),
      modifiedAt: DateTime.now(),
      children: children,
    );
  }

  /// Create a Dart file with default content
  factory FileEntity.dartFile({
    required String id,
    required String name,
    required String path,
    String? className,
  }) {
    final classNameClean = className ?? _getClassName(name);
    final content = '''// $name
// Generated by Flutter IDE Mobile

import 'package:flutter/material.dart';

class $classNameClean extends StatelessWidget {
  const $classNameClean({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('$classNameClean'),
      ),
    );
  }
}
''';
    return FileEntity.file(
      id: id,
      name: name,
      path: path,
      content: content,
    );
  }

  /// Get file extension
  static String? _getExtension(String fileName) {
    final dotIndex = fileName.lastIndexOf('.');
    if (dotIndex == -1 || dotIndex == fileName.length - 1) {
      return null;
    }
    return fileName.substring(dotIndex + 1);
  }

  /// Extract class name from file name
  static String _getClassName(String fileName) {
    final name = fileName.replaceAll('.dart', '');
    if (name.isEmpty) return 'NewClass';
    
    // Convert snake_case or kebab-case to PascalCase
    final parts = name.split(RegExp(r'[_-]'));
    return parts.map((part) => 
      part.isNotEmpty ? '${part[0].toUpperCase()}${part.substring(1)}' : ''
    ).join('');
  }

  /// Check if this is a Dart file
  bool get isDartFile => extension == 'dart';

  /// Check if this is a YAML file
  bool get isYamlFile => extension == 'yaml' || extension == 'yml';

  /// Check if this is a JSON file
  bool get isJsonFile => extension == 'json';

  /// Check if this is a configuration file
  bool get isConfigFile => 
      isYamlFile || isJsonFile || 
      name == 'pubspec.yaml' || name == 'analysis_options.yaml';

  /// Get the file icon based on extension
  String get icon {
    switch (type) {
      case FileEntityType.directory:
        return 'folder';
      case FileEntityType.file:
        switch (extension) {
          case 'dart':
            return 'code';
          case 'yaml':
          case 'yml':
            return 'settings';
          case 'json':
            return 'data_object';
          case 'md':
            return 'description';
          case 'png':
          case 'jpg':
          case 'jpeg':
          case 'gif':
          case 'svg':
            return 'image';
          default:
            return 'insert_drive_file';
        }
    }
  }

  /// Copy with new values
  FileEntity copyWith({
    String? id,
    String? name,
    String? path,
    FileEntityType? type,
    String? content,
    DateTime? createdAt,
    DateTime? modifiedAt,
    bool? isDirty,
    List<FileEntity>? children,
    String? extension,
  }) {
    return FileEntity(
      id: id ?? this.id,
      name: name ?? this.name,
      path: path ?? this.path,
      type: type ?? this.type,
      content: content ?? this.content,
      createdAt: createdAt ?? this.createdAt,
      modifiedAt: modifiedAt ?? this.modifiedAt,
      isDirty: isDirty ?? this.isDirty,
      children: children ?? this.children,
      extension: extension ?? this.extension,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path;

  @override
  int get hashCode => id.hashCode ^ path.hashCode;

  @override
  String toString() => 'FileEntity(name: $name, path: $path, type: $type)';
}

/// File entity types
enum FileEntityType {
  file,
  directory,
}

/// File system tree structure
class FileSystemTree {
  final List<FileEntity> roots;
  final Map<String, FileEntity> fileMap;

  const FileSystemTree({
    this.roots = const [],
    this.fileMap = const {},
  });

  /// Create a default Flutter project structure
  factory FileSystemTree.defaultProject() {
    final mainFile = FileEntity.dartFile(
      id: 'main_dart',
      name: 'main.dart',
      path: '/lib/main.dart',
      className: 'MyApp',
    );

    final homePage = FileEntity.dartFile(
      id: 'home_page',
      name: 'home_page.dart',
      path: '/lib/home_page.dart',
      className: 'HomePage',
    );

    final libDir = FileEntity.directory(
      id: 'lib_dir',
      name: 'lib',
      path: '/lib',
      children: [mainFile, homePage],
    );

    final androidDir = FileEntity.directory(
      id: 'android_dir',
      name: 'android',
      path: '/android',
      children: [],
    );

    final iosDir = FileEntity.directory(
      id: 'ios_dir',
      name: 'ios',
      path: '/ios',
      children: [],
    );

    final assetsDir = FileEntity.directory(
      id: 'assets_dir',
      name: 'assets',
      path: '/assets',
      children: [],
    );

    final pubspec = FileEntity.file(
      id: 'pubspec',
      name: 'pubspec.yaml',
      path: '/pubspec.yaml',
      content: _defaultPubspec,
    );

    final analysisOptions = FileEntity.file(
      id: 'analysis_options',
      name: 'analysis_options.yaml',
      path: '/analysis_options.yaml',
      content: _defaultAnalysisOptions,
    );

    final roots = [libDir, androidDir, iosDir, assetsDir, pubspec, analysisOptions];

    final fileMap = <String, FileEntity>{};
    void addToMap(FileEntity entity) {
      fileMap[entity.path] = entity;
      for (final child in entity.children) {
        addToMap(child);
      }
    }
    for (final root in roots) {
      addToMap(root);
    }

    return FileSystemTree(roots: roots, fileMap: fileMap);
  }

  /// Find a file by path
  FileEntity? findByPath(String path) => fileMap[path];

  /// Find a file by id
  FileEntity? findById(String id) {
    for (final file in fileMap.values) {
      if (file.id == id) return file;
    }
    return null;
  }

  /// Get all Dart files
  List<FileEntity> get dartFiles => 
      fileMap.values.where((f) => f.isDartFile).toList();

  /// Copy with updated file
  FileSystemTree updateFile(FileEntity file) {
    final newMap = Map<String, FileEntity>.from(fileMap);
    newMap[file.path] = file;
    return FileSystemTree(roots: roots, fileMap: newMap);
  }

  static const String _defaultPubspec = '''name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
''';

  static const String _defaultAnalysisOptions = '''include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
''';
}